# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class GameStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetActions = channel.unary_unary(
                '/protos.Game/GetActions',
                request_serializer=service__pb2.State.SerializeToString,
                response_deserializer=service__pb2.Actions.FromString,
                )
        self.SendServerParams = channel.unary_unary(
                '/protos.Game/SendServerParams',
                request_serializer=service__pb2.ServerParam.SerializeToString,
                response_deserializer=service__pb2.Empty.FromString,
                )
        self.SendPlayerParams = channel.unary_unary(
                '/protos.Game/SendPlayerParams',
                request_serializer=service__pb2.PlayerParam.SerializeToString,
                response_deserializer=service__pb2.Empty.FromString,
                )
        self.SendPlayerType = channel.unary_unary(
                '/protos.Game/SendPlayerType',
                request_serializer=service__pb2.PlayerType.SerializeToString,
                response_deserializer=service__pb2.Empty.FromString,
                )


class GameServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetActions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendServerParams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendPlayerParams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendPlayerType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetActions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActions,
                    request_deserializer=service__pb2.State.FromString,
                    response_serializer=service__pb2.Actions.SerializeToString,
            ),
            'SendServerParams': grpc.unary_unary_rpc_method_handler(
                    servicer.SendServerParams,
                    request_deserializer=service__pb2.ServerParam.FromString,
                    response_serializer=service__pb2.Empty.SerializeToString,
            ),
            'SendPlayerParams': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPlayerParams,
                    request_deserializer=service__pb2.PlayerParam.FromString,
                    response_serializer=service__pb2.Empty.SerializeToString,
            ),
            'SendPlayerType': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPlayerType,
                    request_deserializer=service__pb2.PlayerType.FromString,
                    response_serializer=service__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protos.Game', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Game(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetActions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Game/GetActions',
            service__pb2.State.SerializeToString,
            service__pb2.Actions.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendServerParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Game/SendServerParams',
            service__pb2.ServerParam.SerializeToString,
            service__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendPlayerParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Game/SendPlayerParams',
            service__pb2.PlayerParam.SerializeToString,
            service__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendPlayerType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Game/SendPlayerType',
            service__pb2.PlayerType.SerializeToString,
            service__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
